### ISSUE TITLE
Remote images not showing in PDF

### ISSUE THREAD

**Issue by paulfioravanti** [gitpitch/gitpitch#224]
I seem to be having issues displaying remote images when printing a presentation out to PDF.

All the images for the presentation are hosted on Dropbox (linked to with urls that have the form of `https://www.dropbox.com/s/xxxxx/image.png?dl=1`), and they display inline as expected when viewing the presentation on GitPitch, but when printed to PDF, all I see are broken image icons.

Details about the presentation are here:

- [Presentation Github repo](https://github.com/rails-oceania/roro/tree/da21d4e418948413ce67c8ea3700b58e57979863/2018/11)
- [Presentation on GitPitch](https://gitpitch.com/rails-oceania/roro?p=2018/11/)

Here is an example screenshot of what I'm seeing when I print to PDF:

<img width="1153" alt="images-missing" src="https://user-images.githubusercontent.com/543366/48323955-d0526d80-e682-11e8-97b0-c6ef607d5580.png">

Since ["remote images are supported by GitPitch both within slides and when printing to PDF"](https://twitter.com/gitpitch/status/1061807251864731648), what should I be doing to get them displaying properly?

**Comment by gitpitch** [comment]
Quick bump for this thread. I have been looking into this issue a bit further and while the problem is as reported...GitPitch does not currently follow **301** or **302** redirects, even if it did follow there may be a further issue with the handling of arbitrary query params on asset URLs when printing to PDF. Such as `?dl=1`, on your image asset URLs.

Given the DropBox API requires the `&dl=` query param to indicate downloading rather than rendering in the headers for your images, I believe you currently have just one option to address the issue you reported:

*Add the DropBox image files to your Git repository and reference those files using relative paths*.

I will update this thread if/when the issues raised are fully addressed. For now, the workaround indicated is the way to go.

**Comment by paulfioravanti** [comment]
I can confirm that even after changing some links to the HTTP 200 versions, there was no change in the outputted PDF: the images were still broken (but I'm getting a feeling that generated PDF is cached somewhere(?), so I'll try again later on).

So, I'm guessing that, for now, adding the images to my Github repository will probably be the path of least resistance with regards to expected PDF generation.

Would you foresee a potential fix being made for this in the future since it is, at least for me, unexpected behaviour given the images display correctly in a browser? Or, are there technical limitations around the PDF generation that would prevent this?

**Comment by gitpitch** [comment]
> So, I'm guessing...

Did you see my update to this thread? I explained above that there is in fact just a single workaround for your DropBox URLs at this time. Add your DropBox image assets to your repo.

> Would you foresee a potential fix being made for this in the future...

Sure. As you can see from the update above I have already begun digging into the issue...it turns out there are two distinct issues that will need to be addressed. This won't be fixed today or tomorrow but it's now on my TODO list. I will bump this thread when I have some progress to report.

**Comment by paulfioravanti** [comment]
> Did you see my update to this thread?

Yes, I did see that. Sorry, "I'm guessing" was just a turn-of-phrase: implication of ambiguity in what you wrote was not intended.

> As you can see from the update above I have already begun digging into the issue...it turns out there are two distinct issues that will need to be addressed. This won't be fixed today or tomorrow but it's now on my TODO list. I will bump this thread when I have some progress to report.

Thanks for looking into this. Obviously, no expectation of a specific time to fix was intended, either.

**Comment by gitpitch** [comment]
> but I'm getting a feeling that generated PDF is cached somewhere(?)

I just realized this went unanswered. Yes, any PDF you generate on gitpitch.com will be cached for up to 20 minutes. As PDF generation is rarely time critical and always resource hungry on the server the caching mechanism simply ensures no individual can hog expensive resources, accidentally or otherwise.

**Comment by gitpitch** [comment]
A new patch is live on gitpitch.com that should fix the PDF printing problems reported on this thread. The two underlying issues (1) HTTP redirects and (2) handling asset URLs with arbitrary query params have been addressed.

When you have a chance can you please test and verify everything is now working for your presentation as expected. Thanks.

**Comment by paulfioravanti** [comment]
I can confirm that slide images that are hosted on Dropbox are displaying properly, however, the Dropbox-hosted logo image is still not displaying as expected when printed out to PDF:

<img width="1255" alt="logo-image-not-displaying" src="https://user-images.githubusercontent.com/543366/48686735-a57f9080-ec11-11e8-837f-521c81dcb0d7.png">

**Comment by gitpitch** [comment]
Thanks for testing this. I didn't even notice the logo. I will look into it and bump the thread when I have something new for you to try out.

**Comment by gitpitch** [comment]
Bump. The original patch has been updated so it now applies to both `PITCHME.md` and `PITCHME.yaml` asset dependencies. The `yaml` asset dependencies includes assets such as logos.

The newly updated patch is now live on gitpitch.com.
